apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  progressDeadlineSeconds: 1200
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - hello-world
              - key: "temporary"
                operator: In
                values:
                - "true"
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: hello-world
        image: shamim009/hello-world:master
        env:
          - name: APP_COLOR
            value: "blue"
          - name: BUILD_NUMBER
            value: master
        imagePullPolicy: Always
        resources:
          limits:
            memory: 64Mi
            cpu: 250m
          requests:
            memory: 32Mi
            cpu: 200m
        ports:
        - containerPort: 80
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            scheme: HTTP
            port: 80
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            scheme: HTTP
            port: 80
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: hello-world
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hello-world
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
